name: BranchCI

on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  branch-ci:
    name: Branch CI
    uses: molssi-seamm/devops/.github/workflows/BranchCI.yaml@main
    with:
      src : from_smiles_step
