name: Release

on:
  release:
    types: [published]
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release:
    name: Release
    uses: molssi-seamm/devops/.github/workflows/Release.yaml@main
    with:
      src : from_smiles_step
    secrets: inherit

